name: CI — Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        service:
          - inventoryservice
          - bookingservice
          - orderservice
          - apigateway
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - run: mvn clean test --file ${{ matrix.service }}/pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report-${{ matrix.service }}
          path: ${{ matrix.service }}/target/site/jacoco/
